# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Flos-YGPu__OaMwVj8aETjEcwuYxHM7I
"""

from fastapi import FastAPI

app=FastAPI()

@app.get('/predict')
def predict_model(age:int,sex:str):
    if age<25 or sex=='F':
        return{'Youngter'}
    else:
        return{'Older'}





